### ISSUE TITLE
Kafka batch consumer not working in spring boot

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#10]
Hi,

Can you help me to find problem in [https://stackoverflow.com/questions/57310585/kafka-batch-listener-incorrect-deserializing-message?noredirect=1#comment101114989_57310585](https://stackoverflow.com/questions/57310585/kafka-batch-listener-incorrect-deserializing-message?noredirect=1#comment101114989_57310585)

**Comment by ivangfr** [comment]
@ankit45621 can I close this issue?
