### ISSUE TITLE
While running source state come to FAILED

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#11]
Hi,

I am running source and sing and both running good but while running source get failed with error:

{"name":"online-platform-connector","connector":{"state":"RUNNING","worker_id":"112.1.0.4:8083"},"tasks":[{"id":0,"state":"FAILED","worker_id":"112.1.0.4:8083","trace":"org.apache.kafka.connect.errors.ConnectException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000255' at 61694776, the last event read from '/var/log/mysql/mysql-bin.000255' at 61870834, the last byte read from '/var/log/mysql/mysql-bin.000255' at 61870834. Error code: 1236; SQLSTATE: HY000.\n\tat io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)\n\tat io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:197)\n\tat io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogReader.java:1018)\n\tat com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:950)\n\tat com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:580)\n\tat com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:825)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: com.github.shyiko.mysql.binlog.network.ServerException: A slave with the same server_uuid/server_id as this slave has connected to the master; the first event 'mysql-bin.000255' at 61694776, the last event read from '/var/log/mysql/mysql-bin.000255' at 61870834, the last byte read from '/var/log/mysql/mysql-bin.000255' at 61870834.\n\tat com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:914)\n\t... 3 more\n"}],"type":"source"}

**Comment by ankit45621** [comment]
Hi @ivangfr,

Do you you know the solution for this error?

**Comment by ivangfr** [comment]
Hi, it is very difficult for me to figure out the problem just with this exception.
However, it says _"A slave with the same server_uuid/server_id as this slave has connected to the master"_.
Are you running any kind of master/slave MySQL cluster configuration? Is it well configured?

**Comment by ankit45621** [comment]
Yes we are running master/slave mysql cluster. I am checking configuration

**Comment by ivangfr** [comment]
@ankit45621 can I close this issue?
