### ISSUE TITLE
Regarding working of kafka-connect and consumers in tandem

### ISSUE THREAD

**Issue by utkarshsaraf19** [ivangfr/springboot-kafka-debezium-ksql#14]
Hi ivagfr, I have only one question to you.The consumers code in java which you have created, are they utilizing connectors you have created in kafka-connect or they are seperately working in nature.

**Comment by ivangfr** [comment]
Hi @utkarshsaraf19! No, the connectors are only used by `MySQL`, `Kafka` and `Elasticsearch`. The `Spring Boot` application **kafka-research-consumer** is consuming events directly from `Kafka`, more specifically from the topic `reviews_researchers_institutes_articles`

**Comment by ivangfr** [comment]
Hi @utkarshsaraf19 Did I answer your question? Do you have more questions? Otherwise, I will close this issue. Thanks!
