### ISSUE TITLE
What is use of jdbc-mysql-source-researchdb.json

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#2]
Hi,

As i am seeing file in connector folder `jdbc-mysql-source-researchdb.json` but there is no use found in whole project. Please help me with this file information.

In case topic configured in same file is called at time when DB insert query triggered. How?

**Comment by ivangfr** [comment]
Hi @ankit45621 ,

You are right. `jdbc-mysql-source-researchdb.json` is not used at all in this project.

This connector is a `jdbc` connector, similar to `debezium` connector. In short, the `jdbc` connector poll data from DB from time to time (5s default). It doesn't handle deletion. Meanwhile, `debezium` connector directly to MySQL binlog, so it knows every DB changes.

I've used `jdbc` connector in this project: thttps://github.com/ivangfr/springboot-kafka-connect-streams

**Comment by ankit45621** [comment]
Ok and how the kafka topic name decide in debezium connector?

**Comment by ankit45621** [comment]
Thanks i got answer: 'serverName.databaseName.tableName'

https://debezium.io/docs/connectors/mysql/

Thanks for help
