### ISSUE TITLE
How to configure consumer for two different topic?

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#3]
Hi,

I have two `mysql.researchdb.institute` and `mysql.researchdb.article` avro classes (i.e. ReviewsConsumerInstituteConfig, ReviewsConsumerArticleConfig) and i want to configure both in different classes but i got error:

    The bean 'kafkaListenerContainerFactory', defined in class path resource [com/moglix/netsuitecommunicator/kafka/ReviewsConsumerInstituteConfig.class], could not be registered. A bean with that name has already been defined in class path resource [com/moglix/netsuitecommunicator/kafka/ReviewsConsumerArticleConfig.class] and overriding is disabled.

**Comment by ivangfr** [comment]
Hi, what to you mean about configure `ReviewsConsumerInstituteConfig` and `ReviewsConsumerArticleConfig`?

**Comment by ankit45621** [comment]
'ReviewsConsumerInstituteConfig' and 'ReviewsConsumerArticleConfig' classes are same as 'ReviewConsumerConfig' class in you sample project

**Comment by ankit45621** [comment]
First approach is that i have to use one config class and use any type java concept in same config class. 

I just want to know if you have any other approach for same problem.

**Comment by ivangfr** [comment]
In my code `ReviewsConsumerConfig` is the class where I configure how my app will communicate with Kafka, that is the configuration way you must implement when using `spring-kafka`. For more about it you can check this project, https://github.com/ivangfr/springboot-spring-kafka.

Then, all this configuration is used, in my code, in the class `ReviewsConsumer` (more specifically at `KafkaListener` annotation).

So, you don't need `ReviewsConsumerInstituteConfig` and `ReviewsConsumerArticleConfig`. One is enough. Besides, you must create a `InstituteConsumer` and `ArticleConsumer` that will listen from `mysql.researchdb.institute` and `mysql.researchdb.article` kafka topics, respectivally.

**Comment by ankit45621** [comment]
Thank, but in my case i m not using ksql now but in future we will use that. And for deserializing avro data i am creating avro classes for both 'mysql.researchdb.institute' and 'mysql.researchdb.article' kafka topics.

But you are creating avro class( 'ReviewMessage' ) for one topic only. And in my case there are two avro classes that i have to deserialize.

I have to configure two different avro classes.

Please help me with this problem.

**Comment by ankit45621** [comment]
I got the solution at:

https://stackoverflow.com/a/56935558/6097074
