### ISSUE TITLE
Not able to connect kafka remotly

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#5]
Hi, 

I am trying to connect kafka remotely. When i used advertised-listner then it works for me but the schema registry will failed after docker restart. 

Please help me for this problem.

**Comment by ivangfr** [comment]
Hi, can you give me more details about what you are trying to do, with some samples and error messages?

**Comment by ankit45621** [comment]
Actually i want to access kafka remotely. Please tell me what configuration i have to put

**Comment by ankit45621** [comment]
For now i am closing this issue.

**Comment by ankit45621** [comment]
Hi,

I am using below docker configuration but not able to connect kafka remotely.

    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_BOB://kafka:9092,LISTENER_FRED://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_FRED://11.1.1.23:29092,LISTENER_BOB://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      TZ: "${TZ-Europe/Berlin}"

When i am using telnet <my PC ip> <29092>, this works fine for me but when i tried to  connect kafka from other system, not able to connect.

I am using following configuration:

[https://drive.google.com/file/d/1b0Nk7X5OWaa28mkqe95JXtEEmpdaen7p/view?usp=sharing](https://drive.google.com/file/d/1b0Nk7X5OWaa28mkqe95JXtEEmpdaen7p/view?usp=sharing)

Can you please help me is there anything required in configuration?

**Comment by ankit45621** [comment]
And when i run docker-compose with only zookeeper, mysql, kafka, and kafka-connect without avro(with JSON) then this works fine for me.

**Comment by ankit45621** [comment]
Problem solved by rebuilding docker containers:

docker-compose up -d --force-recreate --build
