### ISSUE TITLE
classcastexception Long cannot be cast to String kafka connector sink

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#6]
Hi,

My source table is: 

Table: cass_supplier_products
Columns:
id	bigint(20) AI PK
id_product	varchar(255)
moglix_supplier_id	varchar(255)
retail_tp	double(12,2)
retail_moq	double(12,2)
bulk_tp	double(12,2)
bulk_moq	double(12,2)
quantity_available	double(12,2)
estimated_delivery	varchar(255)
valid_till	datetime
uploaded_by	varchar(255)
out_of_stock_flag	tinyint(1)
deleted_flag	tinyint(1)
supplier_active_status	tinyint(1)
supplier_retail_flag	tinyint(1)
notify_flag	tinyint(1)
created_on	timestamp
updated_on	timestamp

and while running JDBC sink connector i am getting `ClassCastException: Long cannot be cast to String`. Can you please help me for this issue?

**Comment by ivangfr** [comment]
Hi @ankit45621 , can you also share the JDBC sink connector configuration?

**Comment by ankit45621** [comment]
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:48083/connectors/ \
    -d '{
       "name":"qa_buyer_sink",
                       "config":{
                "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
                "tasks.max": "1",
                "topics.regex": "data_lake.qa_buyer.(.*)",
                "connection.user": "",
                "table.name.format": "qa_buyer_${topic}",
                "connection.password": "",
                "connection.url": "jdbc:mysql://localhost:3306/central_sink",
    "auto.create": "true",
    "insert.mode":"upsert",
    "pk.mode":"record_key",
    "pk.fields":"id",
    "auto.evolve":"true",
    "key.converter":"org.apache.kafka.connect.json.JsonConverter",
    "value.converter":"org.apache.kafka.connect.json.JsonConverter",
    "transforms.unwrap.type": "io.debezium.transforms.UnwrapFromEnvelope",
    "transforms": "route,unwrap,created_on,updated_on",
    "transforms.route.replacement": "$3",
    "transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
    "transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",


    "transforms.created_on.type":"com.abhi.connect.timestamp.TimeStampConverter$Value",
    "transforms.created_on.target.type": "string",
    "transforms.created_on.field":"created_on",


    "transforms.updated_on.type":"com.abhi.connect.timestamp.TimeStampConverter$Value",
    "transforms.updated_on.target.type": "string",
    "transforms.updated_on.field":"updated_on"


}}'

**Comment by ivangfr** [comment]
The fields you are getting `Long` to `String` casting exception are `created_on ` and `updated_on`? What is this `com.abhi.connect.timestamp.TimeStampConverter`?

**Comment by ankit45621** [comment]
This(`com.abhi.connect.timestamp.TimeStampConverter`) is my custom Type transform class from `Datetime` type to `String` in target table.

**Comment by ankit45621** [comment]
This is solved by mannually change column type of target table from Long to string.
