### ISSUE TITLE
kafka monitoring in source and sink

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#8]
Hi,

After setup source and sink at my server sometime sink not done for all data. Actually i want to monitor source and sink to check how many data from source not sink. Is there any way to do this?

**Comment by ivangfr** [comment]
Hi, I know that your source connector is from MySQL to Kafka. What about your sink, is it from Kafka to where? I am facing the same problem, but it happens when the data passes through kafka stream. Some records are not processed.

**Comment by ankit45621** [comment]
In my case i am using JDBCConnector for sink

**Comment by ivangfr** [comment]
I don't know if there is some tool to do it. Usually, a simple way to check is to monitor the number of records on the `from` storage and compare with the number on the `to` storage. Maybe, enable `DEBUG` on `kafka-connect`. It can show more info why some records were dropped.

**Comment by ankit45621** [comment]
**I am facing the same problem, but it happens when the data passes through kafka stream**

have you got solution for your problem?

**Comment by ivangfr** [comment]
The problem that I mentioned is still opened. I haven't had time to investigate/solve it yet.

**Comment by ivangfr** [comment]
@ankit45621 can I close this issue?
