### ISSUE TITLE
org.apache.kafka.common.config.ConfigException: Invalid value 200000000000 for configuration message.max.bytes: Not a number of type INT

### ISSUE THREAD

**Issue by ankit45621** [ivangfr/springboot-kafka-debezium-ksql#9]
Hi,

I am trying to configure max kafka message size in docker-compose to 200 GB but i am getting error:

`org.apache.kafka.common.config.ConfigException: Invalid value 200000000000 for configuration message.max.bytes: Not a number of type INT`

Is there any way to put maximum message size in kafka of 200 GB?

**Comment by ankit45621** [comment]
kafka:
    image: confluentinc/cp-kafka:latest
    volumes:
      - "/vol3/kafka-data:/var/lib/kafka/data"
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENERS: LISTENER_BOB://kafka:9092,LISTENER_FRED://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_FRED://kafka.moglilabs.com:29092,LISTENER_BOB://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: '200000000000'

**Comment by ankit45621** [comment]
[https://github.com/confluentinc/cp-helm-charts/issues/235](https://github.com/confluentinc/cp-helm-charts/issues/235)

**Comment by srinathrangaramanujam** [comment]
Message.Max.Bytes is an integer type. U can specify only 2 power 31 - 1(int.max) But u r trying more than 10 digits. Can u try some thing less and why do u need such a high value.?.

**Comment by ankit45621** [comment]
I have test server of 400gb but kafka took all space i.e i am restricted max kafka memory

**Comment by srinathrangaramanujam** [comment]
Okay okay. I get ur problem. I think i answered in both github issues. Lets use this page. So u have something called retention.bytes and log.retention.bytes set that to an optimum value. So kafka ll automatically purge the old data in fifo order..

**Comment by ankit45621** [comment]
Ok i will try

**Comment by ankit45621** [comment]
@Tenseiga Yes this work fine but this provide retention for all topics.

but if i have 4 topic and i want to configure all four combine with retention.byte of 5 GB. How can i configure same?

Below provide configuration for one topic but i want for combine:

kafka-configs.sh --zookeeper localhost:2181 --alter --entity-type topics --entity-name data_lake.online_platform.* --add-config 'retention.bytes=74000000000'

**Comment by srinathrangaramanujam** [comment]
@ankit45621 
Can u do the math say retention bytes for each topics = (max size of combined topics in GB  * 1073741824)/no of topics .i.e in ur case its 5 * 1073741824/4. This is a simple math.

**Comment by ankit45621** [comment]
@tenseiga
I think you didn't understand my question. I just want to put 74 gb to all 5 (distribution should be done by kafka)  not by me because actually i have lots of topics. 

Anyway i did this by configuring all seperatly. 

Thanks
